// Dovzhik Tolya

#include "GAS/Abilities/Tasks/TargetDataUnderMouse.h"

#include "AbilitySystemComponent.h"

UTargetDataUnderMouse* UTargetDataUnderMouse::CreateTargetDataUnderMouse( UGameplayAbility* OwningAbility )
{
	UTargetDataUnderMouse* MyObj = NewAbilityTask<UTargetDataUnderMouse>( OwningAbility );
	return MyObj;
}
void UTargetDataUnderMouse::Activate()
{
	Super::Activate();

	// Even if it's a ListenServer type of game we should send data to server as even if a client is the ListenServer
	// the client still a client and can't replicate data to other clients
	const bool bIsLocallyControlled = Ability->GetCurrentActorInfo()->IsLocallyControlled();
	// Client code
	if ( bIsLocallyControlled )
	{
		SendMouseCursorData();
	}
	// Server code
	else
	{
		// Ability handle
		FGameplayAbilitySpecHandle SpecHandle = GetAbilitySpecHandle();

		// Prediction key which was passed to the GampleAbility on activation
		// Allows server and client to be sure that they are talking about the same ability
		FPredictionKey ActivationPredictionKey = GetActivationPredictionKey();

		// Bind callback to run on receiving TargetData for given ActivationPredictionKey and SpecHandle
		AbilitySystemComponent.Get()->AbilityTargetDataSetDelegate( SpecHandle, ActivationPredictionKey ).AddUObject( this, &UTargetDataUnderMouse::OnTargetDataReplicatedCallback );
		// Call delegates with TargetDataHandle for given ActivationPredictionKay and SpecHandle
		const bool bCalledDelegate = AbilitySystemComponent.Get()->CallReplicatedTargetDataDelegatesIfSet( SpecHandle, ActivationPredictionKey );
		if ( !bCalledDelegate )
		{
			// If TargetDataHandle is not received yet then wait. And when received call all delegates for the Ability
			SetWaitingOnRemotePlayerData();
		}
	}
}

void UTargetDataUnderMouse::SendMouseCursorData()
{
	// How this prediction key works:
	// We create a ScopedPrediction and pass our ASC to the constructor
	// The ASC generates a prediction key inside himself
	// We mark all the operations we want with this ScopedPrediction.
	// Then the server receives a key generated by ASC. ( We pass it in ServerSetReplicatedTargetData )
	// And if the server cancels the ability, it says to a client to revert all changes marked with this very key ( ScopedPrediction ).
	FScopedPredictionWindow ScopedPrediction( AbilitySystemComponent.Get() );

	// Get HitResul
	APlayerController* PC = Ability->GetCurrentActorInfo()->PlayerController.Get();
	FHitResult CursorHit;
	PC->GetHitResultUnderCursor( ECC_Visibility, false, CursorHit );

	//	ServerSetReplicatedTargetData takes DataHandle type so we should wrap our Data in this Handle
	FGameplayAbilityTargetDataHandle DataHandle;
	// TargetData struct to store FHitResult
	FGameplayAbilityTargetData_SingleTargetHit* Data = new FGameplayAbilityTargetData_SingleTargetHit();
	Data->HitResult = CursorHit;
	DataHandle.Add( Data );

	// Ability handle
	FGameplayAbilitySpecHandle SpecHandle = GetAbilitySpecHandle();

	// Prediction key which was passed to the GampleAbility on activation
	// Allows server and client to be sure that they are talking about the same ability
	FPredictionKey ActivationPredictionKey = GetActivationPredictionKey();

	// Pass a prediction key to server so it could revert all predictions made with
	// prediction associated with the key
	FPredictionKey ScopedPreditionKey = AbilitySystemComponent->ScopedPredictionKey;

	// Replicate data to server
	AbilitySystemComponent->ServerSetReplicatedTargetData( SpecHandle, ActivationPredictionKey, DataHandle, FGameplayTag(), ScopedPreditionKey );

	// Checks if ability is still active ( it's written in the function description )
	if ( ShouldBroadcastAbilityTaskDelegates() )
	{
		DataIsReady.Broadcast( DataHandle );
	}
}

void UTargetDataUnderMouse::OnTargetDataReplicatedCallback( const FGameplayAbilityTargetDataHandle& DataHandle, FGameplayTag ActivationTag )
{
	// Ability handle
	FGameplayAbilitySpecHandle SpecHandle = GetAbilitySpecHandle();

	// Prediction key which was passed to the GampleAbility on activation
	// Allows server and client to be sure that they are talking about the same ability
	FPredictionKey ActivationPredictionKey = GetActivationPredictionKey();

	// Clear cache after we used the received data on server
	AbilitySystemComponent->ConsumeClientReplicatedTargetData( SpecHandle, ActivationPredictionKey );
	if ( ShouldBroadcastAbilityTaskDelegates() )
	{
		DataIsReady.Broadcast( DataHandle );
	}
}